import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Card } from 'antd';
import type { FormProps } from 'antd';
import { Button, Checkbox, Form, Input } from 'antd';
import { useWatchAsset } from 'wagmi';

type FieldType = {
  address: string;
  symbol?: string;
  decimals?: number;
  image?: string;
};


const Home: NextPage = () => {


  const { watchAsset } = useWatchAsset()
  
  const onFinish: FormProps<FieldType>['onFinish'] = (values) => {
    console.log('Success:', values);
    watchAsset({
      type: 'ERC20',
      options: {
        address: values.address,
        symbol: values.symbol || '',
        decimals: values.decimals || 18,
        image: values.image || ''
      }
    })
  };
  
  const onFinishFailed: FormProps<FieldType>['onFinishFailed'] = (errorInfo) => {
    console.log('Failed:', errorInfo);
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-center p-4 bg-gray-100">
      <Head>
        <title>Bybit Wallet EVM Dapp DEMO</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <Card title="Add Token" variant="borderless" className='mt-4 w-96'>
        <Form
    name="basic"
    labelCol={{ span: 8 }}
    wrapperCol={{ span: 16 }}
    style={{ maxWidth: 600 }}
    initialValues={{ 
      address: '0xbdF43ecAdC5ceF51B7D1772F722E40596BC1788B',
      symbol: 'SEI',
      decimals: 18,
      image: 'https://assets.coingecko.com/coins/images/1633/large/sei-logo.png?1747034776'
     }}
    onFinish={onFinish}
    onFinishFailed={onFinishFailed}
    autoComplete="off"
  >
    <Form.Item<FieldType>
      label="Address"
      name="address"
      rules={[{ required: true, message: 'Please input your address!' }]}
    >
      <Input />
    </Form.Item>

    <Form.Item<FieldType>
      label="Symbol"
      name="symbol"
      rules={[{ required: false, message: 'Please input your symbol!' }]}
    >
      <Input />
    </Form.Item>

    <Form.Item<FieldType>
      label="Decimals"
      name="decimals"
      rules={[{ required: false, message: 'Please input your decimals!' }]}
    >
      <Input />
    </Form.Item>

    <Form.Item<FieldType>
      label="Image"
      name="image"
      rules={[{ required: false, message: 'Please input your image!' }]}
    >
      <Input />
    </Form.Item>

    <Form.Item label={null}>
      <Button type="primary" htmlType="submit">
        Submit
      </Button>
    </Form.Item>
  </Form>
        </Card>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by Potter Zhang
        </a>
      </footer>
    </div>
  );
};

export default Home;
